export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const LOGIN_TWO_STEP_REQUEST = "LOGIN_TWO_STEP_REQUEST";
export const LOGIN_TWO_STEP_SUCCESS = "LOGIN_TWO_STEP_SUCCESS";
export const LOGIN_TWO_STEP_FAIL = "LOGIN_TWO_STEP_FAIL";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAIL = "GET_USER_FAIL";

export const SEND_VERIFICATION_OTP_REQUEST = "SEND_VERIFICATION_OTP_REQUEST";
export const SEND_VERIFICATION_OTP_SUCCESS = "SEND_VERIFICATION_OTP_SUCCESS";
export const SEND_VERIFICATION_OTP_FAIL = "SEND_VERIFICATION_OTP_FAIL";

export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST =
  "ENABLE_TWO_STEP_AUTHENTICATION_REQUEST";
export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS =
  "ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS";
export const ENABLE_TWO_STEP_AUTHENTICATION_FAIL =
  "ENABLE_TWO_STEP_AUTHENTICATION_FAIL";

export const VERIFY_OTP_REQUEST = "VERIFY_OTP_REQUEST";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const VERIFY_OTP_FAIL = "VERIFY_OTP_FAIL";

export const SEND_RESET_PASSWORD_REQUEST = "SEND_RESET_PASSWORD_REQUEST";
export const SEND_RESET_PASSWORD_SUCCESS = "SEND_RESET_PASSWORD_SUCCESS";
export const SEND_RESET_PASSWORD_FAIL = "SEND_RESET_PASSWORD_FAIL";

export const VERIFY_RESET_PASSWORD_REQUEST = "VERIFY_RESET_PASSWORD_REQUEST";
export const VERIFY_RESET_PASSWORD_SUCCESS = "VERIFY_RESET_PASSWORD_SUCCESS";
export const VERIFY_RESET_PASSWORD_FAIL = "VERIFY_RESET_PASSWORD_FAIL";

export const LOGOUT = "LOGOUT";